import React from 'react';
import { ScrollView, Text, SafeAreaView } from 'react-native';
import { FlatList } from 'react-native-gesture-handler';
import SliderlItem from '../SliderlItem';
import styles from './styles';
import MovieItem from '../MovieItem';

const HorizontalSlider = ({ sliderType, navigation }) => {
  const fakeData = [
    {
      cast_id: 14,
      character: 'Woody (voice)',
      credit_id: '52fe4284c3a36847f8024f95',
      gender: 2,
      id: 31,
      name: 'Tom Hanks',
      order: 0,
      profile_path: '/2gY92j2lkNHL2cThBhPmgXLd5PL.jpg',
    },
    {
      cast_id: 15,
      character: 'Buzz Lightyear (voice)',
      credit_id: '52fe4284c3a36847f8024f99',
      gender: 2,
      id: 12898,
      name: 'Tim Allen',
      order: 1,
      profile_path: '/84VfGVV4A9C6Rb0pgsCvxSVqnX.jpg',
    },
    {
      cast_id: 16,
      character: 'Mr. Potato Head (voice)',
      credit_id: '52fe4284c3a36847f8024f9d',
      gender: 2,
      id: 7167,
      name: 'Don Rickles',
      order: 2,
      profile_path: '/iJLQV4dcbTUgxlWJakjDldzlMXS.jpg',
    },
    {
      cast_id: 17,
      character: 'Slinky Dog (voice)',
      credit_id: '52fe4284c3a36847f8024fa1',
      gender: 2,
      id: 12899,
      name: 'Jim Varney',
      order: 3,
      profile_path: '/j2De8KaACIbi4IX8WfUZGmCW1k2.jpg',
    },
    {
      cast_id: 18,
      character: 'Rex (voice)',
      credit_id: '52fe4284c3a36847f8024fa5',
      gender: 2,
      id: 12900,
      name: 'Wallace Shawn',
      order: 4,
      profile_path: '/tiiz0t7fFiaeoujUyejzIiLRYpu.jpg',
    },
    {
      cast_id: 19,
      character: 'Hamm (voice)',
      credit_id: '52fe4284c3a36847f8024fa9',
      gender: 2,
      id: 7907,
      name: 'John Ratzenberger',
      order: 5,
      profile_path: '/oRtDEOuIO1yDhTz5dORBdxXuLMO.jpg',
    },
    {
      cast_id: 20,
      character: 'Bo Peep (voice)',
      credit_id: '52fe4284c3a36847f8024fad',
      gender: 1,
      id: 8873,
      name: 'Annie Potts',
      order: 6,
      profile_path: '/hWIzkAH7jkSkxBfwdudxbSPxeno.jpg',
    },
    {
      cast_id: 26,
      character: 'Andy (voice)',
      credit_id: '52fe4284c3a36847f8024fc1',
      gender: 2,
      id: 1116442,
      name: 'John Morris',
      order: 7,
      profile_path: '/xMtT5UlPYZX7tobi55YFcdgyFp.jpg',
    },
    {
      cast_id: 22,
      character: 'Sid (voice)',
      credit_id: '52fe4284c3a36847f8024fb1',
      gender: 2,
      id: 12901,
      name: 'Erik von Detten',
      order: 8,
      profile_path: null,
    },
    {
      cast_id: 23,
      character: 'Mrs. Davis (voice)',
      credit_id: '52fe4284c3a36847f8024fb5',
      gender: 1,
      id: 12133,
      name: 'Laurie Metcalf',
      order: 9,
      profile_path: '/oHhTbuv9eNJV4YlgizhCkZsPV0N.jpg',
    },
    {
      cast_id: 24,
      character: 'Sergeant (voice)',
      credit_id: '52fe4284c3a36847f8024fb9',
      gender: 2,
      id: 8655,
      name: 'R. Lee Ermey',
      order: 10,
      profile_path: '/zLYTdLpgvxkIp8CFFoUz6WLCdCG.jpg',
    },
    {
      cast_id: 25,
      character: 'Hannah (voice)',
      credit_id: '52fe4284c3a36847f8024fbd',
      gender: 1,
      id: 12903,
      name: 'Sarah Freeman',
      order: 11,
      profile_path: '/rvGeGaPLNaJeFDmEvsKRklE6Xaf.jpg',
    },
    {
      cast_id: 27,
      character: 'TV Announcer (voice)',
      credit_id: '52fe4284c3a36847f8024fc5',
      gender: 2,
      id: 37221,
      name: 'Penn Jillette',
      order: 12,
      profile_path: '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg',
    },
    {
      cast_id: 300,
      character: 'Shark / Rocky Gibraltar (voice)',
      credit_id: '5aa599ad9251412787027f71',
      gender: 2,
      id: 19545,
      name: 'Jack Angel',
      order: 13,
      profile_path: null,
    },
    {
      cast_id: 301,
      character: 'Wounded Soldier (voice)',
      credit_id: '5aa599edc3a3687bfc02cbf2',
      gender: 0,
      id: 1266092,
      name: 'Spencer Aste',
      order: 14,
      profile_path: null,
    },
    {
      cast_id: 302,
      character: 'Local Announcer (voice)',
      credit_id: '5aa59b229251412781026d69',
      gender: 2,
      id: 94038,
      name: 'Greg Berg',
      order: 15,
      profile_path: null,
    },
    {
      cast_id: 303,
      character: 'Kid (voice)',
      credit_id: '5aa59b4e925141278d027723',
      gender: 0,
      id: 1202809,
      name: 'Lisa Bradley',
      order: 16,
      profile_path: null,
    },
    {
      cast_id: 304,
      character: 'Kid (voice)',
      credit_id: '5aa59b7b92514127840277c1',
      gender: 0,
      id: 134713,
      name: 'Kendall Cunningham',
      order: 17,
      profile_path: null,
    },
    {
      cast_id: 305,
      character: 'Aliens / Pizza Planet Announcer (voice)',
      credit_id: '5aa59b8d0e0a26075a02c4d4',
      gender: 1,
      id: 73016,
      name: 'Debi Derryberry',
      order: 18,
      profile_path: '/aB3016rMAcuEEyytdQskRQwm8ff.jpg',
    },
    {
      cast_id: 306,
      character: 'Kid (voice)',
      credit_id: '5aa59bc0c3a3687c0c02aa21',
      gender: 2,
      id: 186614,
      name: 'Cody Dorkin',
      order: 19,
      profile_path: null,
    },
    {
      cast_id: 310,
      character: 'Monotone Announcer (voice)',
      credit_id: '5aa59c2e0e0a26075d02c5cd',
      gender: 2,
      id: 84213,
      name: 'Bill Farmer',
      order: 20,
      profile_path: '/fIlqDsf9Ze31rVhShnR9dHgkYlD.jpg',
    },
    {
      cast_id: 311,
      character: 'Mission Control (voice)',
      credit_id: '5aa59c62925141278d027807',
      gender: 2,
      id: 1122227,
      name: 'Craig Good',
      order: 21,
      profile_path: null,
    },
    {
      cast_id: 307,
      character: 'Kid (voice)',
      credit_id: '5aa59bd0c3a3687bfc02cdf4',
      gender: 0,
      id: 1017469,
      name: 'Gregory Grudt',
      order: 22,
      profile_path: null,
    },
    {
      cast_id: 312,
      character: 'Burned Rag Doll (voice)',
      credit_id: '5aa59c75925141277e02772d',
      gender: 0,
      id: 1217873,
      name: 'Danielle Judovits',
      order: 23,
      profile_path: null,
    },
    {
      cast_id: 308,
      character: 'Kid (voice)',
      credit_id: '5aa59bde0e0a26074d0285ce',
      gender: 0,
      id: 1266095,
      name: 'Sam Lasseter',
      order: 24,
      profile_path: null,
    },
    {
      cast_id: 309,
      character: 'Kid (voice)',
      credit_id: '5aa59c0b0e0a26075402b8a5',
      gender: 1,
      id: 178710,
      name: 'Brittany Levenbrown',
      order: 25,
      profile_path: null,
    },
    {
      cast_id: 162,
      character: 'Mom (voice)',
      credit_id: '59f546f592514141ed005c7f',
      gender: 1,
      id: 214701,
      name: 'Sherry Lynn',
      order: 26,
      profile_path: null,
    },
    {
      cast_id: 313,
      character: 'Kid (voice)',
      credit_id: '5aa59ca4c3a3687c2502c393',
      gender: 2,
      id: 79020,
      name: 'Scott McAfee',
      order: 27,
      profile_path: null,
    },
    {
      cast_id: 339,
      character: "Sid's Mom (voice)",
      credit_id: '5e6ea17eb1f68d0019d87b0f',
      gender: 1,
      id: 84493,
      name: 'Mickie McGowan',
      order: 28,
      profile_path: null,
    },
    {
      cast_id: 314,
      character: 'Kid (voice)',
      credit_id: '5aa59cb20e0a26074b02c841',
      gender: 2,
      id: 166406,
      name: "Ryan O'Donohue",
      order: 29,
      profile_path: null,
    },
    {
      cast_id: 315,
      character: 'Aliens / Robot / Mr. Spell (voice)',
      credit_id: '5aa59cbf0e0a260760027438',
      gender: 2,
      id: 7882,
      name: 'Jeff Pidgeon',
      order: 30,
      profile_path: null,
    },
    {
      cast_id: 316,
      character: 'Pizza Delivery Guy / Angry Driver #2 (voice)',
      credit_id: '5aa59cce925141279302851e',
      gender: 2,
      id: 61968,
      name: 'Patrick Pinney',
      order: 31,
      profile_path: '/t2dM1NsGohkGpETRUF56W8vEbpA.jpg',
    },
    {
      cast_id: 317,
      character: 'Pizza Planet Announcer / Pizza Planet Guard (voice)',
      credit_id: '5aa59cdec3a3687c2502c3d9',
      gender: 2,
      id: 61969,
      name: 'Phil Proctor',
      order: 32,
      profile_path: '/wAfx3qAEvcsLpEEIP0zwdhuDIcW.jpg',
    },
    {
      cast_id: 318,
      character: 'Gas Station Attendant (voice)',
      credit_id: '5aa59ced0e0a26075a02c62b',
      gender: 2,
      id: 157626,
      name: 'Jan Rabson',
      order: 33,
      profile_path: null,
    },
    {
      cast_id: 319,
      character: 'Lenny the Binoculars (voice)',
      credit_id: '5aa59cfa0e0a260760027472',
      gender: 2,
      id: 7911,
      name: 'Joe Ranft',
      order: 34,
      profile_path: '/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg',
    },
    {
      cast_id: 320,
      character: 'Commercial Chorus (voice)',
      credit_id: '5aa59d0bc3a3687bff02cc99',
      gender: 2,
      id: 7,
      name: 'Andrew Stanton',
      order: 35,
      profile_path: '/gasNitCwepbqNcYBmDHpsCgZH0I.jpg',
    },
    {
      cast_id: 321,
      character: 'Kid (voice)',
      credit_id: '5aa59d18925141277e0277a1',
      gender: 2,
      id: 158124,
      name: 'Shane Sweet',
      order: 36,
      profile_path: null,
    },
    {
      cast_id: 322,
      character: 'Timon (voice) (archive footage) (uncredited)',
      credit_id: '5aa59d539251412781026f2c',
      gender: 2,
      id: 78729,
      name: 'Nathan Lane',
      order: 37,
      profile_path: '/qXupNWu2g9DsRjd7XGD5smGLWlZ.jpg',
    },
    {
      cast_id: 323,
      character: 'Commercial Chorus #1 (voice) (uncredited)',
      credit_id: '5aa59d62c3a3687c06026721',
      gender: 2,
      id: 7879,
      name: 'John Lasseter',
      order: 38,
      profile_path: '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg',
    },
    {
      cast_id: 324,
      character: 'Pumbaa (voice) (archive footage) (uncredited)',
      credit_id: '5aa59d6fc3a3687c2502c468',
      gender: 2,
      id: 69415,
      name: 'Ernie Sabella',
      order: 39,
      profile_path: '/dBit6gkZfxXqdxO0Ic8CsnLpxyQ.jpg',
    },
  ];

  const fakeSimilarMovies = [
    {
      id: 672,
      video: false,
      vote_count: 14084,
      vote_average: 7.7,
      title: 'Harry Potter and the Chamber of Secrets',
      release_date: '2002-11-13',
      original_language: 'en',
      original_title: 'Harry Potter and the Chamber of Secrets',
      genre_ids: [12, 14],
      backdrop_path: '/bvRnPaai6JL7XHF4K6414DdSHro.jpg',
      adult: false,
      overview:
        'Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.',
      poster_path: '/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg',
      popularity: 50.941,
    },
    {
      id: 674,
      video: false,
      vote_count: 13175,
      vote_average: 7.8,
      title: 'Harry Potter and the Goblet of Fire',
      release_date: '2005-11-16',
      original_language: 'en',
      original_title: 'Harry Potter and the Goblet of Fire',
      genre_ids: [12, 14, 10751],
      backdrop_path: '/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg',
      adult: false,
      overview:
        'Harry starts his fourth year at Hogwarts, competes in the treacherous Triwizard Tournament and faces the evil Lord Voldemort. Ron and Hermione help Harry manage the pressure – but Voldemort lurks, awaiting his chance to destroy Harry and all that he stands for.',
      poster_path: '/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg',
      popularity: 32.75,
    },
    {
      id: 675,
      video: false,
      vote_count: 12789,
      vote_average: 7.7,
      title: 'Harry Potter and the Order of the Phoenix',
      release_date: '2007-06-28',
      original_language: 'en',
      original_title: 'Harry Potter and the Order of the Phoenix',
      genre_ids: [12, 14, 9648],
      backdrop_path: '/7qKWTyYvkyIrWgkUOHiNxHv3FNK.jpg',
      adult: false,
      overview:
        "Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students – dubbed 'Dumbledore's Army' – to defend themselves against the dark arts.",
      poster_path: '/g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg',
      popularity: 35.301,
    },
    {
      id: 673,
      video: false,
      vote_count: 13767,
      vote_average: 8.0,
      title: 'Harry Potter and the Prisoner of Azkaban',
      release_date: '2004-05-31',
      original_language: 'en',
      original_title: 'Harry Potter and the Prisoner of Azkaban',
      genre_ids: [12, 14],
      backdrop_path: '/vbk5CfaAHOjQPSAcYm6AoRRz2Af.jpg',
      adult: false,
      overview:
        'Harry, Ron and Hermione return to Hogwarts for another magic-filled year. Harry comes face to face with danger yet again, this time in the form of escaped convict, Sirius Black—and turns to sympathetic Professor Lupin for help.',
      poster_path: '/uDQibffYgssdiqx7izO57wdLc6.jpg',
      popularity: 38.329,
    },
    {
      id: 767,
      video: false,
      vote_count: 12492,
      vote_average: 7.7,
      title: 'Harry Potter and the Half-Blood Prince',
      release_date: '2009-07-07',
      original_language: 'en',
      original_title: 'Harry Potter and the Half-Blood Prince',
      genre_ids: [12, 14],
      backdrop_path: '/kT8bDEAgEYBKhRJtqM97qTw6uRW.jpg',
      adult: false,
      overview:
        "As Harry begins his sixth year at Hogwarts, he discovers an old book marked as 'Property of the Half-Blood Prince', and begins to learn more about Lord Voldemort's dark past.",
      poster_path: '/Ag21otqbeynZPGjEbzyr3X5Us0j.jpg',
      popularity: 31.665,
    },
    {
      adult: false,
      backdrop_path: '/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg',
      genre_ids: [12, 14],
      id: 12444,
      original_language: 'en',
      original_title: 'Harry Potter and the Deathly Hallows: Part 1',
      overview:
        "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
      poster_path: '/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg',
      release_date: '2010-10-17',
      title: 'Harry Potter and the Deathly Hallows: Part 1',
      video: false,
      vote_average: 7.8,
      vote_count: 12693,
      popularity: 33.696,
    },
    {
      id: 12445,
      video: false,
      vote_count: 13626,
      vote_average: 8.1,
      title: 'Harry Potter and the Deathly Hallows: Part 2',
      release_date: '2011-07-07',
      original_language: 'en',
      original_title: 'Harry Potter and the Deathly Hallows: Part 2',
      genre_ids: [12, 14],
      backdrop_path: '/n5A7brJCjejceZmHyujwUTVgQNC.jpg',
      adult: false,
      overview:
        "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
      poster_path: '/c54HpQmuwXjHq2C9wmoACjxoom3.jpg',
      popularity: 34.281,
    },
    {
      id: 58,
      video: false,
      vote_count: 10900,
      vote_average: 7.2,
      title: "Pirates of the Caribbean: Dead Man's Chest",
      release_date: '2006-06-20',
      original_language: 'en',
      original_title: "Pirates of the Caribbean: Dead Man's Chest",
      genre_ids: [28, 12, 14],
      backdrop_path: '/5gPPx16QWx071VAI1M0RAVKJ6tc.jpg',
      adult: false,
      overview:
        'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davey Jones, he also attempts to avoid eternal damnation.',
      poster_path: '/lAhcKRt0ggTFkeFL95jrGQYaRXs.jpg',
      popularity: 31.718,
    },
    {
      id: 22,
      video: false,
      vote_count: 14358,
      vote_average: 7.7,
      title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
      release_date: '2003-07-09',
      original_language: 'en',
      original_title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
      genre_ids: [28, 12, 14],
      backdrop_path: '/w1hQlA8VYeAgrPNujAYcnm7mdIT.jpg',
      adult: false,
      overview:
        "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
      poster_path: '/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg',
      popularity: 37.249,
    },
    {
      id: 285,
      video: false,
      vote_count: 9724,
      vote_average: 7.2,
      title: "Pirates of the Caribbean: At World's End",
      release_date: '2007-05-19',
      original_language: 'en',
      original_title: "Pirates of the Caribbean: At World's End",
      genre_ids: [28, 12, 14],
      backdrop_path: '/kobscH4qOsYQNTZnkrF5zkPCsvX.jpg',
      adult: false,
      overview:
        'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.',
      poster_path: '/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg',
      popularity: 27.019,
    },
    {
      id: 425,
      video: false,
      vote_count: 8796,
      vote_average: 7.3,
      title: 'Ice Age',
      release_date: '2002-03-10',
      original_language: 'en',
      original_title: 'Ice Age',
      genre_ids: [12, 16, 35, 10751],
      backdrop_path: '/rZADxl1kLwMQJa5o1VHdKrWtOp7.jpg',
      adult: false,
      overview:
        'With the impending ice age almost upon them, a mismatched trio of prehistoric critters – Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth – find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims.',
      poster_path: '/gLhHHZUzeseRXShoDyC4VqLgsNv.jpg',
      popularity: 24.121,
    },
    {
      adult: false,
      backdrop_path: '/uzIGtyS6bbnJzGsPL93WCF1FWm8.jpg',
      genre_ids: [12, 28, 14],
      id: 1865,
      original_language: 'en',
      original_title: 'Pirates of the Caribbean: On Stranger Tides',
      overview:
        "Captain Jack Sparrow crosses paths with a woman from his past, and he's not sure if it's love -- or if she's a ruthless con artist who's using him to find the fabled Fountain of Youth. When she forces him aboard the Queen Anne's Revenge, the ship of the formidable pirate Blackbeard, Jack finds himself on an unexpected adventure in which he doesn't know who to fear more: Blackbeard or the woman from his past.",
      poster_path: '/keGfSvCmYj7CvdRx36OdVrAEibE.jpg',
      release_date: '2011-05-14',
      title: 'Pirates of the Caribbean: On Stranger Tides',
      video: false,
      vote_average: 6.5,
      vote_count: 9829,
      popularity: 29.36,
    },
    {
      id: 411,
      video: false,
      vote_count: 6870,
      vote_average: 7.1,
      title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
      release_date: '2005-12-07',
      original_language: 'en',
      original_title:
        'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
      genre_ids: [12, 14, 10751],
      backdrop_path: '/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg',
      adult: false,
      overview:
        "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, the they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
      poster_path: '/kzJip9vndXYSKQHCgekrgqbnUrA.jpg',
      popularity: 24.399,
    },
    {
      id: 12,
      video: false,
      vote_count: 13450,
      vote_average: 7.8,
      title: 'Finding Nemo',
      release_date: '2003-05-30',
      original_language: 'en',
      original_title: 'Finding Nemo',
      genre_ids: [16, 10751],
      backdrop_path: '/6AASwDhTzI0V0JWZS8hVu6b9086.jpg',
      adult: false,
      overview:
        "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
      poster_path: '/xVNSgrsvpcAHPnyKf2phYxyppNZ.jpg',
      popularity: 28.842,
    },
    {
      id: 808,
      video: false,
      vote_count: 10468,
      vote_average: 7.6,
      title: 'Shrek',
      release_date: '2001-05-18',
      original_language: 'en',
      original_title: 'Shrek',
      genre_ids: [12, 16, 35, 14, 10751],
      backdrop_path: '/2l5UHZBcp9cx1PwKLdisJ0gV9jB.jpg',
      adult: false,
      overview:
        "It ain't easy bein' green -- especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an unlikely compatriot -- a wisecracking donkey.",
      poster_path: '/o04jZs5SXhbvhqO4981W7KJXOWZ.jpg',
      popularity: 30.793,
    },
    {
      id: 809,
      video: false,
      vote_count: 7520,
      vote_average: 7.0,
      title: 'Shrek 2',
      release_date: '2004-05-19',
      original_language: 'en',
      original_title: 'Shrek 2',
      genre_ids: [12, 16, 35, 14, 10751],
      backdrop_path: '/eYnigMezyPLEOFykWr2sYucnIJQ.jpg',
      adult: false,
      overview:
        "Shrek, Fiona and Donkey set off to Far, Far Away to meet Fiona's mother and father. But not everyone is happy. Shrek and the King find it hard to get along, and there's tension in the marriage. The fairy godmother discovers that Shrek has married Fiona instead of her Son Prince Charming and sets about destroying their marriage.",
      poster_path: '/kra8EvGDUgntRVjkTcENYzaBIH1.jpg',
      popularity: 24.949,
    },
    {
      id: 557,
      video: false,
      vote_count: 11698,
      vote_average: 7.1,
      title: 'Spider-Man',
      release_date: '2002-05-01',
      original_language: 'en',
      original_title: 'Spider-Man',
      genre_ids: [28, 14],
      backdrop_path: '/vugNEFkYXrR6yjr6ZoawnHNyCmu.jpg',
      adult: false,
      overview:
        'After being bitten by a genetically altered spider, nerdy high school student Peter Parker is endowed with amazing powers to become the Amazing superhero known as Spider-Man.',
      poster_path: '/cqyN8Kt10wCrIUUZX7l5uDJIY0C.jpg',
      popularity: 28.846,
    },
    {
      id: 585,
      video: false,
      vote_count: 12571,
      vote_average: 7.8,
      title: 'Monsters, Inc.',
      release_date: '2001-11-01',
      original_language: 'en',
      original_title: 'Monsters, Inc.',
      genre_ids: [16, 35, 10751],
      backdrop_path: '/sDTnMOJ3H5wI38OxObmCtK7wfd5.jpg',
      adult: false,
      overview:
        "James Sullivan and Mike Wazowski are monsters, they earn their living scaring children and are the best in the business... even though they're more afraid of the children than they are of them. When a child accidentally enters their world, James and Mike suddenly find that kids are not to be afraid of and they uncover a conspiracy that could threaten all children across the world.",
      poster_path: '/8hMd1BIcCwISqxOdo1G4UXCEOI.jpg',
      popularity: 31.196,
    },
    {
      id: 950,
      video: false,
      vote_count: 6779,
      vote_average: 6.6,
      title: 'Ice Age: The Meltdown',
      release_date: '2006-03-29',
      original_language: 'en',
      original_title: 'Ice Age: The Meltdown',
      genre_ids: [12, 16, 35, 10751],
      backdrop_path: '/5oZK7HyK5jXA5XEq3tjZsjOMHNd.jpg',
      adult: false,
      overview:
        "Diego, Manny and Sid return in this sequel to the hit animated movie Ice Age. This time around, the deep freeze is over, and the ice-covered earth is starting to melt, which will destroy the trio's cherished valley. The impending disaster prompts them to reunite and warn all the other beasts about the desperate situation.",
      poster_path: '/eYff7CWPMCKhIGTos2SzTd3VFbA.jpg',
      popularity: 23.642,
    },
    {
      id: 953,
      video: false,
      vote_count: 7309,
      vote_average: 6.8,
      title: 'Madagascar',
      release_date: '2005-05-25',
      original_language: 'en',
      original_title: 'Madagascar',
      genre_ids: [16, 10751],
      backdrop_path: '/8NCftAWfkETwrbf7QwEaDH1xpus.jpg',
      adult: false,
      overview:
        'Alex the lion is the king of the urban jungle, the main attraction at New York’s Central Park Zoo. He and his best friends—Marty the zebra, Melman the giraffe and Gloria the hippo—have spent their whole lives in blissful captivity before an admiring public and with regular meals provided for them. Not content to leave well enough alone, Marty lets his curiosity get the better of him and makes his escape—with the help of some prodigious penguins—to explore the world.',
      poster_path: '/uHkmbxb70IQhV4q94MiBe9dqVqv.jpg',
      popularity: 18.39,
    },
  ];
  const itemToShow = (item: any): JSX.Element => {
    switch (sliderType) {
      case 'cast':
        return (
          <SliderlItem
            image={item.profile_path}
            title={item.name}
            subtitle={item.character}
          />
        );
      case 'movies':
        return (
          <MovieItem
            size="small"
            imageUrl={`https://image.tmdb.org/t/p/original${fakeSimilarMovies[0].poster_path}`}
            title={fakeSimilarMovies[0].original_title}
            navigation={navigation}
            id={item.id}></MovieItem>
        );
    }
  };

  return (
    <SafeAreaView /* horizontal={true} */>
      <FlatList
        horizontal={true}
        numColumns={1}
        keyExtractor={(item: any) => item.id.toString()}
        data={fakeData}
        renderItem={({ item }) => itemToShow(item)}></FlatList>
    </SafeAreaView>
  );
};

export default HorizontalSlider;
